### PR TITLE
account for attributes added dynamically and having a higher version of sequelize

### PR DESCRIPTION
**Pull request by samifahed**
Attributes can be added by appending to the "attributes" field something like this: [ SQLQuery, attribute_name]
support having a higher version of sequelize

### CODE REVIEW

**Comment by overlookmotel** [comment]
Sorry for slow response.

I've reviewed this PR, but I can't understand what it's supposed to do. Can you clarify please?

I've updated the dependencies to allow for versions of sequelize from 2.0.0 onwards.

**Comment by samifahed** [comment]
The first problem we had is adding dynamic attributes to a find query of the form "[ SQLQuery, attribute_name]", and that was fixed in the first commit, the second problem we had is that the module overrides the getters of all the models that we have, even if they don't have virtual fields, now what we did is remove the instanceGet that overrides the getters, which is maybe not the right thing to do because then the virtual model stays loaded within the model.

**Comment by overlookmotel** [comment]
OK, I think I understand what you mean now. When you say

> dynamic attributes to a find query of the form "[ SQLQuery, attribute_name ]"

...do you mean something that creates SQL of the form `SQLQuery AS attribute_name`?

Yes, you're right, this is not supported at present. To be honest this isn't something I need so I'm realistically not going to have time to implement it. If you want to implement that'd be great and I'd be happy to merge it into the module.

However, it'd need to add the functionality you need without breaking other functionality that sequelize-virtual-fields supports. Your PR at present causes a lot of the tests to fail, which shows it's breaking things.

Would you like to have a go at this?

**Comment by samifahed** [comment]
OK, I have updated the pull request to be on a working state now, this should be enough to handle the `SQLQuery AS attribute_name` case.

**Comment by overlookmotel** [comment]
Can you please rebase it onto latest master (or, even better, `dev` branch)?
Also, could be good to only skip the error if an option is set - for most users the error message for non-existent fields would be useful.

**Comment by owcd** [comment]
didn't notice this PR is still open when I applied the experimental fix for #2 on our fork. I rebased the two fixes on top of the current master and put them into #3 and #4. Please close this.

**Comment by overlookmotel** [comment]
Closed as per request

**Pull request closed without merging**
